export { default as Header } from "./Header/Header";
export { default as NavMenu } from "./NavMenu/NavMenu";
export { default as Section1 } from "./Section1/Section1";
export { default as Section2 } from "./Section2/Section2";
export { default as Section3 } from "./Section3/Section3";
export { default as Section4 } from "./Section4";
export { default as Section5 } from "./Section5";
export { default as Carousel } from "./Carousel/Carousel";
export { default as Footer } from "./Footer";
